// 부설주차장 설치기준 — 멀티리전(16개 지자체) 건물 용도별 큐레이션.
//   ※ 13개 중 수원만 보류(일반 주차장 설치 조례가 법제처 ordin DB에 없음 — 보훈시설 조례만 존재).
// nat = 국가(주차장법 시행령 별표1), sel = 도시 조례(별표). 모두 graph.json 원문 대조.
//   ※ 부산·인천 별표는 HWP 첨부 → 빌더 HWP 폴백으로 graph.json 에 표 본문 수록.
//   ※ 인천은 도시지역/지구단위 vs 관리지역 2단 기준 → sel=도시지역, note=관리지역.
//   strict = 서울/부산/인천이 국가보다 강화(면적기준↓ = 더 많은 주차).

const PK = "주차장법";
const PK_D = "주차장법 시행령";

const refs = (조례조, 조례별표) => [
  `${PK}/제19조`, `${PK_D}/제6조`, `${PK_D}/별표1`, 조례조, 조례별표,
];

// 국가 기준(시행령 별표1) — 도시 공통 baseline
const NAT = {
  wirak: "시설면적 100㎡당 1대",
  munhwa: "시설면적 150㎡당 1대",
  geunsaeng: "시설면적 200㎡당 1대",
  dandok: "50㎡ 초과~150㎡ 이하: 1대 / 150㎡ 초과: 1+{(면적−150)/100}",
  gongdong: "「주택건설기준 등에 관한 규정」 제27조①에 따라 산정",
  golf: "골프장 1홀 10대 / 골프연습장 1타석 1대 / 옥외수영장 정원 15명당 1대 / 관람장 정원 100명당 1대",
  suryeon: "시설면적 350㎡당 1대",
  changgo: "시설면적 400㎡당 1대",
  etc: "시설면적 300㎡당 1대",
};

export const PARKING_REGIONS = [
  {
    code: "11", name: "서울특별시",
    refs: refs("서울특별시 주차장 설치 및 관리 조례/제20조", "서울특별시 주차장 설치 및 관리 조례/별표2"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 67㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "eopmu", label: "업무시설(외국공관·오피스텔 제외)", nat: NAT.munhwa, sel: "일반업무 100㎡당 1대 / 공공업무 200㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 134㎡당 1대", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "국가 기준과 동일", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "좌동 + 세대(호실)당 최소 1대(전용 30㎡↓ 0.5대·60㎡↓ 0.8대)", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 233㎡당 1대", strict: true },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 267㎡당 1대", strict: true },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "200㎡당 1대 (학교 250㎡·학생기숙사 400㎡)", strict: true },
    ],
  },
  {
    code: "26", name: "부산광역시",
    refs: refs("부산광역시 주차장 설치 및 관리 조례/제14조", "부산광역시 주차장 설치 및 관리 조례/별표7"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 67㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 134㎡당 1대", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "50㎡ 초과~180㎡ 이하: 1대 / 180㎡ 초과: 1+{(면적−180)/120}", strict: false, note: "부산은 기준면적 180㎡·가산 120㎡(국가 150·100과 다름)" },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "좌동 + 세대당 최소 1대(전용 30㎡↓ 0.5대)", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물 (학생기숙사·데이터센터 400㎡)", nat: NAT.etc, sel: "시설면적 200㎡당 1대", strict: true },
    ],
  },
  {
    code: "28", name: "인천광역시",
    refs: refs("인천광역시 주차장 설치 및 관리 조례/제15조", "인천광역시 주차장 설치 및 관리 조례/별표2"),
    note: "인천은 도시지역·지구단위계획구역 / 관리지역 2단 기준. 아래는 도시지역 기준.",
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 70㎡당 1대", note: "관리지역 100㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", note: "관리지역 150㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 134㎡당 1대 (생활숙박은 호실당 1대)", note: "관리지역 200㎡당 1대", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "국가 기준과 동일", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 산정 + 세대당 최소 1대", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "골프장 1홀 15대 / 골프연습장 0.7타석당 1대 / 옥외수영장 정원 10명당 1대 / 관람장 정원 70명당 1대", note: "관리지역은 국가 기준과 동일", strict: true },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "imdae", label: "임대형 기숙사", nat: "—", sel: "시설면적 150㎡당 1대", note: "관리지역 200㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물 (학생기숙사 350㎡)", nat: NAT.etc, sel: "시설면적 200㎡당 1대", note: "관리지역 300㎡당 1대", strict: true },
    ],
  },
  {
    code: "27", name: "대구광역시",
    refs: refs("대구광역시 주차장 설치 및 관리 조례/제15조", "대구광역시 주차장 설치 및 관리 조례/별표2"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 70㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 150㎡당 1대 (생활숙박은 호실당 1대)", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "국가 기준과 동일", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 산정 + 세대(오피스텔 호실)당 1대(전용 30㎡↓ 0.5대·60㎡↓ 1대) / 도시형 원룸 0.9대(30㎡미만 0.7)", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "gisuksa", label: "학생용 기숙사", nat: "—", sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "시설면적 300㎡당 1대", strict: false },
    ],
  },
  {
    code: "31", name: "울산광역시",
    refs: refs("울산광역시 주차장 설치 및 관리 조례/제13조", "울산광역시 주차장 설치 및 관리 조례/별표6"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 67㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 134㎡당 1대", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "국가 기준과 동일", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 산정 + 오피스텔 세대(호실)당 1대 / 도시형 소형 0.9대(30㎡미만 0.7)", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설 / 공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "수련시설 233㎡당 1대 / 공장·발전 350㎡당 1대 (국가산단 정유·화학·발전 400㎡)", strict: true },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 266㎡당 1대", strict: true },
      { key: "etc", label: "데이터센터 / 그 밖의 건축물", nat: NAT.etc, sel: "데이터센터 400㎡당 1대 / 그 밖 200㎡당 1대", strict: true },
    ],
  },
  {
    code: "36", name: "세종특별자치시",
    refs: refs("세종특별자치시 주차장 설치 및 관리 조례/제17조", "세종특별자치시 주차장 설치 및 관리 조례/별표2"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 100㎡당 1대", strict: false },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 134㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 150㎡당 1대", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "국가 기준과 동일", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "전용 85㎡↓ 85㎡당 1대·85㎡초과 70㎡당 1대 + 세대당 1대 / 도시형 원룸 0.9대(30㎡미만 0.75)", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "골프장 1홀 15대 / 골프연습장 1타석 1.5대 / 옥외수영장 15명·관람장 100명당 1대", strict: true },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 300㎡당 1대 (산업단지 공장 400㎡)", strict: true },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "시설면적 300㎡당 1대", strict: false },
    ],
  },
  {
    code: "41460", name: "용인시",
    refs: refs("용인시 주차장 설치 및 관리 조례/제23조", "용인시 주차장 설치 및 관리 조례/별표7"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 67㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 132㎡당 1대 (생활숙박 100㎡당 1대·호실당 0.7대 중 큰 값)", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "국가 기준과 동일", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 산정 + 세대당 1대 / 도시형 1대(전용 30~60㎡ 0.7·30㎡미만 0.6)", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "골프장 1홀 15대 / 골프연습장 1타석 1대 / 옥외수영장 8명·관람장 50명당 1대", strict: true },
      { key: "suryeon", label: "수련시설·공장(지식산업센터 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대 (첨단공장 10만㎡ 초과분 800㎡)", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "gisuksa", label: "학생용 기숙사", nat: "—", sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "그 밖 200㎡당 1대 (데이터센터 400㎡)", strict: true },
    ],
  },
  {
    code: "41280", name: "고양시",
    refs: refs("고양시 주차장 설치 및 관리 조례/제22조", "고양시 주차장 설치 및 관리 조례/별표7"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 67㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대 (문화집회·종교 75㎡당 1대)", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 134㎡당 1대 (생활숙박 세대·호실당 1대)", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "50㎡ 초과~100㎡: 1대 / 100㎡ 초과: 1+{(면적−100)/87}", note: "고양은 기준·가산 면적이 국가(150·100)와 다름(100·87)", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 산정 + 세대·호실당 1대 / 도시형 1대(전용 30~60㎡ 0.9·30㎡미만 0.6)", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "골프장 1홀 15대 / 골프연습장 1타석 1대 / 옥외수영장 15명·관람장 100명당 1대", strict: true },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "1만㎡ 미만 250㎡당 1대 / 1만㎡ 이상 350㎡당 1대", strict: true },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 300㎡당 1대", strict: true },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "그 밖 200㎡당 1대 (학생기숙사 400㎡·데이터센터 200㎡·주택전시장 75㎡)", strict: true },
    ],
  },
  {
    code: "48120", name: "창원시",
    refs: refs("창원시 주차장 설치 및 관리 조례/제14조", "창원시 주차장 설치 및 관리 조례/별표6"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 100㎡당 1대 (중심상업·성산구 용호·상남 상업지역 80㎡)", strict: false },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대 (집회장 75㎡당 1대)", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "국가 기준과 동일", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 산정 + 세대(오피스텔 호실)당 1대 / 도시형 원룸 0.7대", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "gisuksa", label: "학생용 기숙사", nat: "—", sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "시설면적 300㎡당 1대", strict: false },
    ],
  },
  {
    code: "50", name: "제주특별자치도",
    refs: refs("제주특별자치도 주차장 설치 및 관리 조례/제22조", "제주특별자치도 주차장 설치 및 관리 조례/별표6"),
    note: "제주는 '가'지역(주로 동지역)·'나'지역 2단 기준. 아래는 '가'지역 기준.",
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 60㎡당 1대", note: "'나'지역 80㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 80㎡당 1대", note: "'나'지역 100㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 120㎡당 1대 (생활숙박 1객실당 1대)", note: "'나'지역 150㎡당 1대", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "50㎡ 초과~100㎡: 1대 / 100㎡ 초과: 1+{(면적−100)/65}", note: "제주는 기준·가산 면적이 국가(150·100)와 다름(100·65)", strict: false },
      { key: "gongdong", label: "다가구·다세대·공동주택·오피스텔", nat: NAT.gongdong, sel: "공동주택 85㎡당 1대 또는 세대당 1대 중 큰 값 / 원룸 전용 40㎡당 1대 또는 세대당 0.9(30㎡미만 0.7) / 오피스텔 1실당 1대", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "골프장 1홀 10대 / 골프연습장 1타석 1.5대 / 옥외수영장 15명·관람장 100명당 1대", strict: true },
      { key: "etc", label: "그 밖의 건축물(수련·공장·창고 포함)", nat: NAT.etc, sel: "시설면적 200㎡당 1대", strict: true },
    ],
  },
  {
    code: "29", name: "광주광역시",
    refs: refs("광주광역시 주차장 조례/제11조", "광주광역시 주차장 조례/별표1"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 67㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 134㎡당 1대", strict: true },
      { key: "dandok", label: "단독주택(다가구 제외)", nat: NAT.dandok, sel: "국가 기준과 동일", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 산정 + 세대(오피스텔 호실)당 1대(다가구 전용 30㎡↓ 0.5대) / 도시형 원룸 주택건설기준 제27조", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "gisuksa", label: "학생용 기숙사", nat: "—", sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "시설면적 200㎡당 1대", strict: true },
    ],
  },
  {
    code: "30", name: "대전광역시",
    refs: refs("대전광역시 주차장 조례/제16조", "대전광역시 주차장 조례/별표1"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 67㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·업무·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 134㎡당 1대", strict: true },
      { key: "dandok", label: "단독·다중주택(다가구 제외)", nat: NAT.dandok, sel: "단독주택 국가와 동일 / 다중주택 150㎡ 초과분 50㎡당 1대", note: "다중주택은 가산면적이 국가(100㎡)보다 강화(50㎡)", strict: false },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 산정 + 세대(호실)당 1대(다가구 전용 30㎡↓ 0.5대) / 원룸형 주택건설기준 제27조", strict: true },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "골프장 1홀 15대 / 골프연습장 1타석 1.5대 / 옥외수영장 15인·관람장 100인당 1대", strict: true },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 200㎡당 1대 (산업단지 공장 450㎡)", strict: true },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "gisuksa", label: "학생용 기숙사", nat: "—", sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "시설면적 200㎡당 1대", strict: true },
    ],
  },
  {
    code: "41130", name: "성남시",
    refs: refs("성남시 주차장 설치 및 관리 운영에 관한 조례/제20조", "성남시 주차장 설치 및 관리 운영에 관한 조례/별표3"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "일반지역 100㎡당 1대 / 지구단위계획구역 70㎡당 1대", strict: false },
      { key: "munhwa", label: "문화·집회·종교·판매시설", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 135㎡당 1대", strict: true },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 규정 제27조 산정", strict: false },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "시설면적 300㎡당 1대", strict: false },
    ],
  },
  {
    code: "43110", name: "청주시",
    refs: refs("청주시 주차장 조례/제15조", "청주시 주차장 조례/별표7"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 67㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·판매·운수·의료·운동·방송국·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대 (예식장·집회장 80㎡당 1대)", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 150㎡당 1대", strict: true },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 규정 제27조 산정", strict: false },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "시설면적 300㎡당 1대", strict: false },
    ],
  },
  {
    code: "45110", name: "전주시",
    refs: refs("전주시 주차장 조례/제13조", "전주시 주차장 조례/별표7"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 80㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·장례식장", nat: NAT.munhwa, sel: "시설면적 120㎡당 1대 (예식장·장례식장 80㎡당 1대)", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 150㎡당 1대 (생활숙박시설 100㎡당 1대 또는 호실당 0.7대)", strict: true },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 산정 / 오피스텔 전용 60㎡↓ 호실당 0.7대", strict: false },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "시설면적 300㎡당 1대", strict: false },
    ],
  },
  {
    code: "44130", name: "천안시",
    refs: refs("천안시 주차장 조례/제11조", "천안시 주차장 조례/별표2"),
    uses: [
      { key: "wirak", label: "위락시설", nat: NAT.wirak, sel: "시설면적 70㎡당 1대", strict: true },
      { key: "munhwa", label: "문화·집회·종교·판매·운수·의료·운동·장례식장", nat: NAT.munhwa, sel: "시설면적 100㎡당 1대", strict: true },
      { key: "geunsaeng", label: "제1·2종 근린생활시설, 숙박시설", nat: NAT.geunsaeng, sel: "시설면적 135㎡당 1대", strict: true },
      { key: "gongdong", label: "다가구·공동주택·오피스텔", nat: NAT.gongdong, sel: "주택건설기준 규정 제27조 산정", strict: false },
      { key: "golf", label: "골프장·골프연습장·옥외수영장·관람장", nat: NAT.golf, sel: "국가 기준과 동일", strict: false },
      { key: "suryeon", label: "수련시설·공장(아파트형 제외)·발전시설", nat: NAT.suryeon, sel: "시설면적 350㎡당 1대", strict: false },
      { key: "changgo", label: "창고시설", nat: NAT.changgo, sel: "시설면적 400㎡당 1대", strict: false },
      { key: "etc", label: "그 밖의 건축물", nat: NAT.etc, sel: "시설면적 300㎡당 1대", strict: false },
    ],
  },
];
