// 자동 생성(LLM 보조) — builder/gen_setback_llm.py. 신규 도시 대지안의공지(이격).
const A58 = "건축법/제58조";
const AD80 = "건축법 시행령/제80의2조";
const AD_BP = "건축법 시행령/별표2";

export const SETBACK_AUTO = [
  { code: "41190", name: "부천시",
    refs: [A58, AD80, AD_BP, "부천시 건축 조례/제27의2조", "부천시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 5m↑(15층 이하 3m↑) / 연립주택 2m↑ / 다세대주택 1m↑ (상업지역 제외, 상업지역 내 창문 있는 부분 공동주택 2m↑)", strict: true }, note: "상업지역 내 공동주택은 인접대지경계선 방향 창문 있는 부분에 한해 2m↑ 적용" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "2m↑ (상업지역 제외)", strict: false }, note: "바닥면적 합계 1,000㎡↑인 판매·숙박·문화집회·종교시설 기준" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 그 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 그 외 2m↑", strict: false }, note: "바닥면적 합계 500㎡↑ 공장 기준; 전용·일반공업지역 및 산업단지 제외. 인접경계 창고는 별표에 명시 없음(공장만 규정)" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑", strict: false }, note: "가~라(건축선) 및 가~바(인접경계) 적용 제외된 그 밖의 모든 건축물" },
    ] },
  { code: "41270", name: "안산시",
    refs: [A58, AD80, AD_BP, "안산시 건축 조례/제26조", "안산시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "해당 없음", strict: false }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
    ] },
  { code: "41360", name: "남양주시",
    refs: [A58, AD80, AD_BP, "남양주시 건축 조례/제27조", "남양주시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립주택 1.5m↑ / 다세대주택 1m↑", strict: true }, note: "인접경계 기준: 상업지역 스프링클러 설치 공동주택 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑(한옥: 처마선 0.5m↑, 외벽선 1m↑)", strict: false }, note: "전용주거지역 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m↑", strict: false }, note: "건축선: 바닥면적 합계 1,000㎡↑ 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접경계: 상업지역 아닌 지역 동일 용도 1,000㎡↑" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "바닥면적 합계 500㎡↑ 공장·창고(전용·일반공업지역 및 산업단지 제외); 부속용도 건축물 완화 규정 있음" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑(한옥: 처마선 0.5m↑, 외벽선 1m↑)", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑(한옥: 처마선 0.5m↑, 외벽선 1m↑)", strict: false }, note: "건축선: 일반·전용주거지역 내 연면적 200㎡ 미만 주택·근린생활시설 제외" },
    ] },
  { code: "41170", name: "안양시",
    refs: [A58, AD80, AD_BP, "안양시 건축 조례/제30조", "안양시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트(폭 12m 이상 도로 접한 부분 또는 30세대 미만) 5m 이상(그 외 3m 이상) / 연립 2m 이상 / 다세대 1m 이상 / 주상복합아파트(상업지역) 3m 이상", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "건축선 후퇴만 규정; 아파트 괄호 안 수치는 조건부 완화값(3m 이상)" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "전용주거지역 1m 이상", strict: false }, note: "인접 대지경계선 후퇴만 규정; 국가 하한(1m)과 동일" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "모든 지역 3m 이상 / 다중이용건축물(1만㎡ 이상) 3m 이상(4m 이상)", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "상업지역이 아닌 지역 1,000㎡ 이상 2m 이상", strict: false }, note: "다중이용건축물 괄호 안 4m는 강화 조건; 인접경계 국가 하한(1.5m)보다 완화된 2m 규정" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m 이상 / 그 밖의 지역 3m 이상", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m 이상 / 그 밖의 지역 2m 이상", strict: false }, note: "전용·일반공업지역 및 산업단지 내 공장·창고는 적용 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "바닥면적 합계 2,000㎡ 이상 1.5m 이상 / 그 밖의 모든 건축물 1m 이상", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표 인접 대지경계선 항목에 '그 밖의 건축물' 규정 없음" },
    ] },
  { code: "41220", name: "평택시",
    refs: [A58, AD80, AD_BP, "평택시 건축 조례/제30조", "평택시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 4m↑ / 연립주택 3m↑ / 다세대주택 1m↑ (상업지역 공동주택 제외)", strict: true }, note: "인접경계 연립주택 3m↑는 국가 하한(1.5m)보다 강화; 상업지역 공동주택은 인접경계 규정 미적용" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외), 인접경계 1m↑" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑ (바닥면적 합계 1,000㎡↑인 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설)", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m↑ (상업지역 아닌 지역, 바닥면적 합계 1,000㎡↑인 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설)", strict: false }, note: "건축선 3m↑는 국가 하한(3m) 동일; 인접경계 1.5m↑는 국가 하한(1.5m) 동일" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑ (바닥면적 합계 500㎡↑, 전용·일반공업지역 및 산업단지 제외)", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑ (바닥면적 합계 500㎡↑, 전용·일반공업지역 및 산업단지 제외)", strict: false }, note: "전용공업지역·일반공업지역·산업단지 내 공장·창고는 적용 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑ (20m↑ 도로에 접한 모든 건축물)", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑", strict: false }, note: "건축선은 20m 이상 도로에 접한 건축물에 한해 적용; 인접경계는 그 밖의 모든 건축물 0.5m↑" },
    ] },
  { code: "41390", name: "시흥시",
    refs: [A58, AD80, AD_BP, "시흥시 건축 조례/제28의2조", "시흥시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 6m↑(도시형생활주택 3m↑) / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 6m↑(도시형생활주택 3m↑) / 연립주택 1.5m↑ / 다세대주택 0.5m↑ (상업지역 제외)", strict: true }, note: "인접경계 기준은 상업지역에서 건축하는 공동주택 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑ (한옥: 처마선 1m↑, 외벽선 1.5m↑)", strict: false }, note: "전용주거지역 건축물(공동주택 제외); 건축선 후퇴 별표 미규정" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑: 1.5m↑ (상업지역 제외)", strict: false }, note: "인접경계 기준은 상업지역에서 건축하는 건축물 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "전용·일반공업지역 및 산업단지 내 공장·창고 제외; 바닥면적 500㎡↑" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑ (한옥: 처마선 1m↑, 외벽선 1.5m↑)", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑ (한옥: 처마선 0.5m↑, 외벽선 1m↑)", strict: false }, note: "그 밖의 건축물 기준" },
    ] },
  { code: "41480", name: "파주시",
    refs: [A58, AD80, AD_BP, "파주시 건축 조례/제28조", "파주시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑ / 연립주택 3m↑ / 다세대주택 2m↑(3세대 이하 1m↑)", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 4m↑ / 연립주택 3m↑ / 다세대주택 2m↑(3세대 이하 1m↑) / 상업지역 제외", strict: true }, note: "인접경계선 기준: 상업지역에서 건축하는 공동주택은 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외), 인접 대지경계선 기준" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑(상업지역 제외): 1.5m↑", strict: false }, note: "건축선 기준은 여관·여인숙 제외, 전시장·동식물원 제외; 인접경계선 기준은 상업지역 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑(부속건축물 1.5m↑)", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "전용공업지역·일반공업지역·산업단지 내 공장·창고는 제외; 창고는 건축선 부속건축물 특례 미적용" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "너비 6m↑ 도로에 접하는 모든 건축물: 1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑", strict: false }, note: "건축선 기준은 너비 6m 이상 도로에 접하는 경우에만 적용" },
    ] },
  { code: "41570", name: "김포시",
    refs: [A58, AD80, AD_BP, "김포시 건축조례/제27조", "김포시 건축조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "해당 없음", strict: false }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
    ] },
  { code: "41210", name: "광명시",
    refs: [A58, AD80, AD_BP, "광명시 건축 조례/제29조", "광명시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "건축선 후퇴만 규정; 인접 대지경계선 후퇴 별표에 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "인접 대지경계선 표에서 전용주거지역 건축물(공동주택 제외) 1m↑" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑: 1.5m↑", strict: false }, note: "건축선 표 나항 3m↑, 인접경계선 표 나항 1.5m↑" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "500㎡↑: 준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "500㎡↑: 준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "창고 포함(인접경계선 표); 전용·일반공업지역 및 산업단지 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "건축선 표 마항 기타 건축물 1m↑; 인접경계선 표에 기타 건축물 항목 없음" },
    ] },
  { code: "41410", name: "군포시",
    refs: [A58, AD80, AD_BP, "군포시 건축 조례/제31조", "군포시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 6m / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, note: "인접경계 아파트는 '이상' 표기 없이 6m 고정; 상업지역 스프링클러 설치 공동주택은 인접경계 규정 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외), 인접경계 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "3m↑", strict: true }, note: "바닥면적 합계 1,000㎡↑ 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접경계는 상업지역 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "바닥면적 합계 500㎡↑ 공장·창고; 전용·일반공업지역 및 산업단지 내 건축물 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑", strict: false } },
    ] },
  { code: "41450", name: "하남시",
    refs: [A58, AD80, AD_BP, "하남시 건축 조례/제27조", "하남시 건축 조례/별표5"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "해당 없음", strict: false }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "별표에 공동주택 관련 규정 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "해당 없음", strict: false }, note: "별표에 전용주거지역 건축물(공동주택 제외) 관련 규정 없음" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m 이상", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m 이상(상업지역 내 스프링클러 설치 건축물 제외)", strict: false }, note: "바닥면적 1,000㎡ 이상 판매·숙박(여관·여인숙 제외)·문화집회(전시장·동식물원 제외)·종교시설 적용" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m 이상 / 그 외 3m 이상", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "공장: 준공업지역 1m 이상 / 그 외 2m 이상 / 창고: 1m 이상", strict: false }, note: "바닥면적 500㎡ 이상, 전용·일반공업지역 및 산업단지 내 공장·창고 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표에 그 밖의 건축물 관련 규정 없음" },
    ] },
  { code: "41370", name: "오산시",
    refs: [A58, AD80, AD_BP, "오산시 건축 조례/제30조", "오산시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트: 30세대 이상 5m↑, 30세대 미만 3m↑, 사업승인대상 6m↑, 부대·복리시설 2m↑ / 연립주택: 3m↑ / 다세대주택: 1.5m↑(20m 이상 도로 2m↑)", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트: 30세대 이상 5m↑, 30세대 미만 3m↑, 사업승인대상 6m↑, 부대·복리시설 2m↑ / 연립주택: 3m↑ / 다세대주택: 1.5m↑", strict: true }, note: "오피스텔·생활숙박시설과 복합 건축 시 합산 세대(실·호)로 산정; 상업지역 스프링클러 설치 공동주택은 인접경계 적용 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외)에 한함" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑ / 3,000㎡↑(다중이용): 3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑(상업지역 제외): 2m↑ / 3,000㎡↑ 다중이용(연면적 2만㎡↑ 또는 10층↑): 3m↑ / 1만㎡↑~2만㎡↑ 미만: 2m↑ / 1만㎡↑ 미만 다중이용: 1.5m↑", strict: true }, note: "인접경계 1,000㎡↑ 기준은 상업지역 건축물 제외; 다중이용 건축물은 연면적·층수에 따라 차등 적용" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역: 1.5m↑ / 준공업지역 외: 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역: 1m↑ / 준공업지역 외: 1.5m↑", strict: false }, note: "전용공업지역·일반공업지역 및 산업단지 내 공장·창고는 적용 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "20m↑ 도로: 2m↑ / 10m↑ 도로: 1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표상 '위에서 정하지 않는 모든 건축물'에 해당; 인접경계 기준은 별표에 규정 없음" },
    ] },
  { code: "41630", name: "양주시",
    refs: [A58, AD80, AD_BP, "남양주시 건축 조례/제27조", "양주시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립주택 1.5m↑ / 다세대주택 1m↑", strict: true }, note: "인접경계 상업지역 내 스프링클러 설치 공동주택 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑ (한옥: 처마선 2m 이하, 외벽선 1m↑)", strict: false }, note: "공동주택 제외" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "상업지역 아닌 지역 2m↑", strict: false }, note: "건축선: 일반숙박시설·전시장·동식물원 제외; 인접경계: 상업지역 제외 조건 동일" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑ (부속용도 건축물 2m↑)", strict: true }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "전용·일반공업지역 및 산업단지 내 공장·창고 제외; 창고도 동일 기준 적용" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "격리병원·장례식장 6m↑ / 위험물저장·자동차관련·자원순환·묘지관련 2m↑ / 그 밖의 모든 건축물 1m↑ (한옥 외벽선 1m↑)", strict: true }, boundary: { nat: "0.5~6m", sel: "격리병원·장례식장 3m↑ / 위험물저장·자동차관련·자원순환·묘지관련 1.5m↑ / 그 밖의 모든 건축물 0.5m↑", strict: true }, note: "건축선 격리병원·장례식장 6m↑는 국가 기준 상한 적용; 인접경계 격리병원·장례식장은 국가 기준 대비 강화" },
    ] },
  { code: "41500", name: "이천시",
    refs: [A58, AD80, AD_BP, "이천시 건축 조례/제52의2조", "이천시 건축 조례/별표2"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립주택 1.5m↑ / 다세대주택 1m↑", strict: true }, note: "인접경계 상업지역 내 스프링클러 설치 공동주택은 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: true }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "상업지역 아닌 지역 1.5m↑", strict: false }, note: "건축선: 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설 바닥면적 1,000㎡↑" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 그 외 3m↑ (부속건축물 2m↑)", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 그 외 1.5m↑", strict: false }, note: "전용공업지역·일반공업지역·산업단지 내 공장·창고는 제외; 창고 건축선 부속건축물 단서는 공장 항목에만 명시" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑ (연면적 2,000㎡↑ 건축물)", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑", strict: false }, note: "건축선은 연면적 2,000㎡↑ 건축물에 적용; 인접경계는 가~바목 제외한 건축물에 0.5m↑" },
    ] },
  { code: "41310", name: "구리시",
    refs: [A58, AD80, AD_BP, "구리시 건축 조례/제29조", "구리시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립주택 1.5m↑ / 다세대주택 1m↑", strict: true }, note: "상업지역 공동주택으로 스프링클러 등 자동식 소화설비 설치 시 인접 대지경계선 후퇴 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역에 건축하는 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m↑", strict: false }, note: "바닥면적 합계 1,000㎡↑ 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접 대지경계선은 상업지역 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "바닥면적 합계 500㎡↑ 공장·창고; 전용공업지역·일반공업지역·산업단지 내 건축물 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑", strict: false }, note: "가목~마목에 해당되지 아니하는 건축물" },
    ] },
  { code: "41550", name: "안성시",
    refs: [A58, AD80, AD_BP, "안성시 건축 조례/제31조", "안성시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 6m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 6m↑ / 연립주택 2m↑ / 다세대주택 1m↑ (상업지역 제외)", strict: true }, note: "인접 대지경계선 기준: 상업지역에서 건축하는 공동주택은 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외), 인접 대지경계선 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m↑ (상업지역 제외)", strict: false }, note: "건축선: 바닥면적 합계 1,000㎡↑ 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접경계: 상업지역 건축물 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "바닥면적 합계 500㎡↑ 공장·창고(전용·일반공업지역 및 산업단지 제외); 창고는 인접경계선 별표에 농림지역 창고(200㎡↑) 별도 규정 있음" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "한옥: 처마선·외벽선 1m↑ / 12m↑ 도로에 접한 건축물: 1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "한옥: 처마선·외벽선 1m↑ / 농림지역 창고(200㎡↑): 높이 9m↓ 1.5m↑·높이 9m↑ 3m↑ / 그 밖의 모든 건축물: 0.5m↑", strict: false }, note: "인접 대지경계선 그 밖의 모든 건축물 0.5m↑는 인접대지경계 소유자와 합의한 경우 제외" },
    ] },
  { code: "41650", name: "포천시",
    refs: [A58, AD80, AD_BP, "포천시 건축 조례/제28조", "포천시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 6.0m / 연립주택 4.0m / 다세대 2.0m", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 6.0m / 연립주택 4.0m / 다세대 1.0m 이상(채광창 벽면 3.0m 이상), 상업지역 제외", strict: true }, note: "건축선: 국가 하한 대비 고정값 적용(아파트·연립 상향, 다세대 상향); 인접경계: 상업지역 공동주택 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1.0m 이상", strict: false }, note: "전용주거지역 건축물(공동주택 제외), 인접경계만 규정" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡ 이상: 3.0m 이상", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡ 이상: 1.5m 이상(상업지역 제외)", strict: false }, note: "일반숙박시설·생활숙박시설 제외; 전시장·동식물원 제외; 상업지역 건축물은 인접경계 적용 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m 이상 / 준공업지역 외 3.0m 이상", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1.0m 이상 / 준공업지역 외 1.5m 이상", strict: false }, note: "바닥면적 500㎡ 이상 공장·창고; 전용공업·일반공업지역 및 산업단지 내 건축 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1.0m 이상", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m", strict: false }, note: "그 밖의 건축물" },
    ] },
  { code: "41430", name: "의왕시",
    refs: [A58, AD80, AD_BP, "의왕시 건축 조례/제29조", "의왕시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑ (두 세대 다세대주택 0.5m↑)", strict: true }, note: "인접경계 공동주택은 상업지역 내 스프링클러 설치 건축물 제외; 두 세대 다세대주택 인접경계 0.5m↑ 특례" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외) 인접경계 1m↑" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "3m↑ (상업지역이 아닌 지역, 1,000㎡↑)", strict: false }, note: "건축선: 바닥면적 합계 1,000㎡↑인 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접경계: 상업지역 제외 조건 동일" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 2m↑", strict: false }, note: "바닥면적 합계 500㎡↑ 공장·창고; 전용·일반공업지역 및 산업단지 내 건축물 제외; 창고는 인접경계 별표에 미기재(공장 항목 준용)" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑", strict: false }, note: "그 밖의 모든 건축물" },
    ] },
  { code: "41290", name: "과천시",
    refs: [A58, AD80, AD_BP, "과천시 건축 조례/제25조", "과천시 건축 조례/별표2"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 6m 이상 / 연립 2m 이상 / 다세대 1.5m 이상", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 4m 이상 / 연립 2m 이상 / 다세대 1m 이상 (상업지역 공동주택 제외)", strict: true }, note: "건축선: 처마 기준 아파트 5.5m↑·연립 1.5m↑·다세대 1m↑ 병기; 인접경계: 처마 기준 아파트 3.5m↑·연립 1.5m↑·다세대 0.5m↑ 병기" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m 이상", strict: false }, note: "인접경계 전용주거지역(공동주택 제외) 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m 이상", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "2m 이상 (상업지역 및 맞벽 적용 대상 제외)", strict: true }, note: "건축선: 1,000㎡↑ 판매·숙박·문화집회·종교시설 3m↑; 다중이용건축물(5,000㎡↑) 3m; 인접경계: 동일 대상 2m↑, 다중이용 2m" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m 이상 / 그 외 3m 이상", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m 이상 / 그 외 1.5m 이상", strict: false }, note: "전용·일반공업지역 및 산업단지 제외; 창고도 동일 기준 적용" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m 이상", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m 이상", strict: false }, note: "건축선: 처마 기준 0.5m↑ 병기" },
    ] },
  { code: "51110", name: "춘천시",
    refs: [A58, AD80, AD_BP, "춘천시 건축 조례/제32조", "춘천시 건축 조례/별표6"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "해당 없음", strict: false }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
    ] },
  { code: "51150", name: "강릉시",
    refs: [A58, AD80, AD_BP, "강릉시 건축 조례/제32조", "강릉시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 6m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 6m↑ / 연립주택 2m↑ / 다세대주택 1m↑ (상업지역 제외)", strict: true }, note: "인접 대지경계선 기준은 상업지역에서 건축하는 경우 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외), 바닥면적 기준 없음" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑(상업지역 아닌 지역): 1.5m↑", strict: false }, note: "건축선 기준은 판매·숙박(일반숙박 제외)·의료·운동·관광휴게·문화집회·종교·위락·운수시설 포함; 인접경계는 상업지역 아닌 지역 한정" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "500㎡↑: 준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "500㎡↑: 준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "전용공업지역·일반공업지역·산업단지에서 건축하는 경우 제외; 창고는 건축선 기준에만 포함" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑", strict: false }, note: "법 제59조 맞벽건축 적용 건축물 제외" },
    ] },
  { code: "51170", name: "동해시",
    refs: [A58, AD80, AD_BP, "동해시 건축 조례/제29조", "동해시 건축 조례/별표5"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 6m↑ / 연립주택 3m↑ / 다세대주택 2m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "건축선 후퇴만 규정; 아파트는 국가 하한(2m) 대비 6m로 상향, 연립·다세대도 국가 하한 대비 상향" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "인접 대지경계선 후퇴 1m↑(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑ / 5,000㎡↑(판매·문화집회·종교·여객·종합병원·관광숙박·16층↑): 5m↑", strict: true }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "상업지역 아닌 지역 1,000㎡↑: 1.5m↑ / 5,000㎡↑(판매·문화집회·종교·여객·종합병원·관광숙박·16층↑): 1.5m↑", strict: false }, note: "5,000㎡↑ 구간에서 건축선 5m↑로 국가 하한(3m) 대비 강화" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 그 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 그 외 1.5m↑", strict: false }, note: "공장·창고 모두 동일 기준 적용; 전용·일반공업지역 및 산업단지 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "업무시설 1,000㎡↑: 3m↑ / 업무시설·문화집회·종교 1,000㎡↑미만: 1m↑ / 위험물저장처리시설: 1.5m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표에서 '그 밖의 건축물' 포괄 규정 없음; 업무·문화집회·종교·위험물 등 개별 항목만 규정" },
    ] },
  { code: "51210", name: "속초시",
    refs: [A58, AD80, AD_BP, "속초시 건축 조례/제36조", "속초시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "해당 없음", strict: false }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 수치 없음" },
    ] },
  { code: "51230", name: "삼척시",
    refs: [A58, AD80, AD_BP, "삼척시 건축 조례/제31조", "삼척시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m 이상 / 연립주택 2m 이상 / 다세대주택 1m 이상", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 6m 이상 / 연립주택 3m 이상 / 다세대주택 2m 이상", strict: true }, note: "상업지역에서 스프링클러 등 자동식 소화설비 설치 공동주택은 인접 대지경계선 후퇴 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m 이상 (한옥: 처마선 1m 이상, 외벽선 2m 이상)", strict: false }, note: "전용주거지역 건축물(공동주택 제외) 기준" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m 이상", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "3m 이상", strict: true }, note: "상업지역에서 스프링클러 등 자동식 소화설비 설치 건축물은 인접 대지경계선 후퇴 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m 이상 / 준공업지역 외의 지역 3m 이상", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m 이상 / 준공업지역 외의 지역 1.5m 이상", strict: false }, note: "전용공업지역·일반공업지역 및 산업단지 내 공장·창고는 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m 이상 (한옥: 처마선 0.5m 이상, 외벽선 1.5m 이상)", strict: false }, boundary: { nat: "0.5~6m", sel: "3m 이상 / 2m 이상 / 1m 이상 / 0.5m 이상 (한옥: 처마선 0.5m 이상, 외벽선 1.5m 이상) (세부 용도별 차등 적용)", strict: false }, note: "바닥면적 1,000㎡ 이상 여부 및 용도(의료시설·위험물·자동차관련·장례·숙박·업무·위락·종교 등)에 따라 후퇴거리 차등; 상업지역 스프링클러 설치 건축물 제외 조건 있음" },
    ] },
  { code: "43130", name: "충주시",
    refs: [A58, AD80, AD_BP, "충주시 건축 조례/제28조", "충주시 건축 조례/별표2"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 6m↑ / 연립주택 3m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 4m↑ / 연립주택 2m↑ / 다세대주택 1m↑ (상업지역 제외)", strict: true }, note: "건축선 아파트는 단일 고정값 6m; 인접경계선은 상업지역 제외 조건 적용" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외), 인접 대지경계선 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "3m↑ (상업지역 제외)", strict: true }, note: "건축선: 바닥면적 합계 1,000㎡↑ 판매·숙박·문화집회·종교시설 3m↑; 인접경계선: 상업지역 제외 조건 명시" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 2m↑ / 준공업지역 외 3m↑", strict: true }, note: "전용·일반공업지역 및 산업단지 제외; 인접경계선 준공업지역 2m↑는 국가 하한(1m↑) 대비 강화" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑", strict: false }, note: "그 밖의 건축물, 인접 대지경계선 0.5m 이상" },
    ] },
  { code: "43150", name: "제천시",
    refs: [A58, AD80, AD_BP, "제천시 건축 조례/제28조", "제천시 건축 조례/별표5"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 5m↑ / 연립주택 2m↑ / 다세대주택 2m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 5m↑ / 연립주택 3m↑ / 다세대주택 2m↑", strict: true }, note: "인접경계 기준은 상업지역에 건축하는 공동주택으로서 자동식 소화설비 설치 건축물 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역에 건축하는 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 5m↑", strict: true }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "상업지역 아닌 지역, 1,000㎡↑: 4m↑", strict: true }, note: "판매시설·숙박시설(일반숙박시설 제외)·문화및집회시설(전시장·동식물원 제외)·종교시설; 다중이용건축물도 건축선 5m↑, 인접경계 4m↑ 적용" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 그 외 4m↑", strict: true }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1.5m↑ / 그 외 3m↑", strict: true }, note: "전용공업지역·일반공업지역·산업단지 내 공장·창고는 제외; 건축선 기준 준공업 외 4m↑는 국가기준(3m↑) 대비 강화" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표에 '그 밖의 건축물' 일반 항목 없음; 조례상 '바'항은 특정 열거 용도(위험물저장시설·동물관련시설 등)에 한정되며 일반 etc 기준은 별표에 미규정" },
    ] },
  { code: "44150", name: "공주시",
    refs: [A58, AD80, AD_BP, "공주시 건축 조례/제27조", "공주시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑ / 연립 2m↑ / 다세대 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 6m↑ / 연립 3m↑(3층 이하 2m↑) / 다세대 3m↑(3층 이하 2m↑, 2층 이하 1m↑)", strict: true }, note: "상업지역 제외 적용" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑(한옥: 처마선 0.5m↑, 외벽선 1m↑)", strict: false }, note: "한옥의 경우 처마선 0.5m, 외벽선 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "상업지역 제외, 3m↑(5층 이하 2m↑)", strict: true }, note: "바닥면적 합계 1,000㎡ 이상 문화·집회·종교·판매·운수·의료(종합병원)·숙박(일반숙박 제외) 시설" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 그 밖의 지역 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "공장: 준공업지역 1m↑ / 그 밖의 지역 3m↑ / 창고: 해당 없음", strict: true }, note: "창고는 인접대지경계선 후퇴 규정 없음(-); 전용·일반공업지역 및 산업단지 내 공장·창고 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "위험물저장·처리시설 2m↑ / 자원순환·묘지·장례식장 3m↑ / 축사·도축장·도계장(1,000㎡ 미만) 3m↑, (1,000㎡ 이상) 5m↑", strict: true }, boundary: { nat: "0.5~6m", sel: "위험물저장·처리시설 2m↑ / 자원순환·묘지·장례식장 6m↑ / 축사·도축장·도계장(1,000㎡ 미만) 2m↑, (1,000㎡ 이상) 6m↑", strict: true }, note: "그 밖의 건축물은 세 가지 세부 용도로 구분하여 각각 상이한 이격거리 적용" },
    ] },
  { code: "44200", name: "아산시",
    refs: [A58, AD80, AD_BP, "아산시 건축 조례/제34조", "아산시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "해당 없음", strict: false }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "해당 없음", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 대지 안의 공지 이격거리 규정 없음" },
    ] },
  { code: "44250", name: "계룡시",
    refs: [A58, AD80, AD_BP, "계룡시 건축 조례/제31조", "계룡시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립 2m↑ / 다세대 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립 1.5m↑ / 다세대 1m↑", strict: true }, note: "건축선 표(마): 아파트 3m↑, 연립 2m↑, 다세대 1m↑ / 인접경계 표(마): 아파트 3m↑, 연립 1.5m↑, 다세대 1m↑" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "인접경계 표 가. 전용주거지역 1m↑" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 판매·문화집회·종교·숙박 각 3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑: 판매·숙박·문화집회·종교 각 1.5m↑", strict: false }, note: "건축선 표(다): 4개 용도 모두 3m↑ / 인접경계 표(다): 4개 용도 모두 1.5m↑" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업 1.5m↑ / 그 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업 1m↑ / 그 외 1.5m↑", strict: false }, note: "공장·창고 동일 기준 적용; 건축선 표(가·나), 인접경계 표(나)" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "다가구(4가구↑) 1m↑ / 의료·노유자·업무·위락 2m↑ / 위험물 3m↑ / 숙박(여관) 2m↑ / 자동차관련 3m↑ / 축사·도축장·도계장 3m↑", strict: true }, boundary: { nat: "0.5~6m", sel: "다가구(4가구↑) 1m↑ / 의료·노유자·업무·위락 1m↑ / 위험물 2m↑ / 숙박(여관) 2m↑ / 자동차관련 2m↑ / 축사·도축장·도계장 3m↑", strict: true }, note: "건축선 표(바) 6개 세부용도 / 인접경계 표(바) 6개 세부용도 각각 상이" },
    ] },
  { code: "52140", name: "익산시",
    refs: [A58, AD80, AD_BP, "익산시 건축조례/제26조", "익산시 건축조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립주택 1.5m↑ / 다세대주택 1m↑ (상업지역 제외)", strict: true }, note: "인접 대지경계선 기준: 상업지역에서 건축하는 공동주택은 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역에서 건축하는 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m↑ (상업지역 제외)", strict: false }, note: "건축선: 바닥면적 합계 1,000㎡↑ 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접경계: 상업지역 건축물 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "바닥면적 합계 500㎡↑ 공장·창고; 전용·일반공업지역 및 산업단지 내 건축물 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑ (바닥면적 합계 1,000㎡↑ 건축물, 한옥의 경우 처마선)", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑ (바닥면적 합계 1,000㎡↑ 건축물, 한옥의 경우 처마선)", strict: false }, note: "그 밖의 건축물 중 바닥면적 합계 1,000㎡ 이상인 건축물에 한함" },
    ] },
  { code: "52180", name: "정읍시",
    refs: [A58, AD80, AD_BP, "정읍시 건축 조례/제22의2조", "정읍시 건축 조례/별표5"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m / 연립주택 3m / 다세대주택 2m", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "건축선 기준만 규정(모든 건축선); 인접 대지경계선 별도 규정 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m 이상", strict: false }, note: "한옥의 경우 처마선 0.5m 이상, 외벽선 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m (바닥면적 합계 1,000㎡ 이상인 판매시설·숙박시설·문화및집회시설·종교시설)", strict: true }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "해당 없음", strict: false }, note: "의료시설·학원·운동시설·관광휴게시설(1,000㎡↑)도 동일하게 3m 적용(라목); 인접 대지경계선 별도 규정 없음" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m / 기타지역 3m (바닥면적 합계 500㎡ 이상인 공장·창고)", strict: true }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "해당 없음", strict: false }, note: "전용공업지역·일반공업지역 및 산업단지는 적용 제외; 인접 대지경계선 별도 규정 없음" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m (3층 이상이고 바닥면적 합계 1,000㎡ 이상인 건축물)", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "도로에 3면 이상 접한 경우 주된 출입구 도로 및 그 외 가장 넓은 도로에 한하여 적용; 인접 대지경계선 별도 규정 없음" },
    ] },
  { code: "52190", name: "남원시",
    refs: [A58, AD80, AD_BP, "남원시 건축 조례/제31조", "남원시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립 2m↑ / 다세대 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립 1.5m↑ / 다세대 1m↑", strict: true }, note: "부대시설·복리시설 및 상업지역 내 공동주택 제외(인접경계선 기준)" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 내 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑(상업지역 제외): 1.5m↑", strict: false }, note: "판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접경계선은 상업지역 제외 조건 명시" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 그 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 그 외 1.5m↑", strict: false }, note: "바닥면적 500㎡↑ 공장·창고; 전용·일반공업지역 및 산업단지 내 공장 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1,000㎡↑: 1m↑(한옥: 처마선 0.5m↑, 외벽선 1m↑)", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑(한옥: 처마선 0.5m↑, 외벽선 1m↑)", strict: false }, note: "건축선 기준은 바닥면적 합계 1,000㎡↑ 건축물에 한함; 인접경계선은 맞벽건축물 제외" },
    ] },
  { code: "46130", name: "여수시",
    refs: [A58, AD80, AD_BP, "여수시 건축 조례/제27조", "여수시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4.5m↑ / 연립주택 2.0m↑ / 다세대주택 1.0m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 4.5m↑ / 연립주택 1.5m↑ / 다세대주택 1.0m↑", strict: true }, note: "상업지역에서 스프링클러 등 자동식 소화설비 설치 공동주택은 인접경계 규정 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1.0m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3.0m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m↑ (상업지역 제외)", strict: false }, note: "바닥면적 합계 1,000㎡↑ 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3.0m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1.0m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "바닥면적 합계 500㎡↑ 공장·창고; 전용·일반공업지역 및 산업단지 내 공장·창고 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "3.0m↑ (한옥 1.0m↑)", strict: true }, boundary: { nat: "0.5~6m", sel: "1.5m↑ (상업지역 제외)", strict: true }, note: "장례식장, 연면적 5,000㎡↑ 건축물 포함; 2면 이상 도로 접할 경우 주도로에 한함(건축선 기준)" },
    ] },
  { code: "46150", name: "순천시",
    refs: [A58, AD80, AD_BP, "순천시 건축 조례/제29조", "순천시 건축 조례/별표2"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 6m↑ / 연립주택 3m↑ / 다세대주택 2m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 6m↑ / 연립주택 3m↑ / 다세대주택 2m↑", strict: true }, note: "상업지역에 건축하는 공동주택으로서 자동식 소화설비를 설치한 경우 인접 대지경계선 후퇴 적용 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역에 건축하는 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "2m↑", strict: false }, note: "건축선: 바닥면적 합계 1,000㎡↑인 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접경계: 상업지역이 아닌 지역에 한함" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "전용공업지역·일반공업지역·산업단지 내 공장·창고는 적용 제외; 인접경계 준공업지역 외 1.5m↑는 국가 하한(1.5m) 동일 수준" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "연면적 5,000㎡↑ 건축물 3m↑ / 장례식장 6m↑ / 한옥 외벽선으로부터 1m↑", strict: true }, boundary: { nat: "0.5~6m", sel: "연면적 5,000㎡↑ 건축물 1m↑ / 장례식장 4m↑ / 한옥 외벽선으로부터 1m↑", strict: true }, note: "가~마목 이외 용도 건축물에 한하며, 장례식장·한옥은 별도 기준 적용" },
    ] },
  { code: "46170", name: "나주시",
    refs: [A58, AD80, AD_BP, "나주시 건축 조례/제36조", "나주시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 6m↑ / 연립주택 3m↑ / 다세대주택 2m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1.5m↑", strict: true }, note: "인접경계 기준: 상업지역 내 스프링클러 설치 공동주택 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑ (한옥: 처마선 0.5m↑, 외벽선 1m↑)", strict: false }, note: "전용주거지역 건축물(공동주택 제외) 인접경계 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "상업지역 아닌 지역 1.5m↑", strict: false }, note: "건축선: 바닥면적 합계 1,000㎡↑ 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "바닥면적 합계 500㎡↑ 공장 및 창고; 전용·일반공업지역 및 산업단지 내 공장 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "연면적 5,000㎡↑: 3m↑ / 장례시설: 6m↑ / 한옥: 외벽선 1m↑", strict: true }, boundary: { nat: "0.5~6m", sel: "연면적 5,000㎡↑: 1m↑ / 장례시설: 3m↑ / 한옥: 처마선 0.5m↑, 외벽선 1m↑", strict: false }, note: "건축선 기준 연면적 5,000㎡↑ 건축물은 대지가 2 이상 도로에 접할 경우 가장 넓은 도로에만 적용" },
    ] },
  { code: "47110", name: "포항시",
    refs: [A58, AD80, AD_BP, "포항시 건축 조례/제28조", "포항시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑(재개발·재건축 3m↑) / 연립 2m↑ / 다세대 2m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 4m↑(재개발·재건축 3m↑) / 연립 2m↑ / 다세대 2m↑(채광창 없는 측벽 1m↑)", strict: true }, note: "인접경계 다세대는 채광창 없는 측벽 부분 1m↑ 적용; 상업지역 공동주택은 인접경계 규정 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "해당 없음", strict: false }, note: "전용주거지역 건축물(공동주택 제외)은 인접경계 항목에 '-'로 표기되어 구체 수치 없음" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑ / 5,000㎡↑: 6m↑", strict: true }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑(상업지역 제외): 3m↑ / 5,000㎡↑(상업지역 제외): 5m↑", strict: true }, note: "건축선 기준 5,000㎡↑는 6m↑; 인접경계 기준 5,000㎡↑는 5m↑(상업지역 제외)" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "공장: 준공업 2m↑ / 그 외 5m↑ / 창고: 준공업 2m↑ / 그 외 3m↑", strict: true }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "공장: 준공업 1.5m↑ / 그 외 2.5m↑", strict: true }, note: "건축선: 전용·일반공업지역 및 산업단지 내 공장·창고 제외; 인접경계: 창고시설 항목 별표에 미기재" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑(제2종근린생활시설 중 종교집회장·장례식장, 학원, 노유자시설)", strict: true }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표상 '그 밖의 건축물' 일반 항목은 없으며, 바항(종교집회장·장례식장·학원·노유자시설)에 1m↑ 규정" },
    ] },
  { code: "47130", name: "경주시",
    refs: [A58, AD80, AD_BP, "경주시 건축 조례/제28조", "경주시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑ / 연립주택 2m↑ / 다세대 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 4m↑ / 연립주택 2m↑ / 다세대 1m↑", strict: true }, note: "상업지역에 스프링클러 등 자동식 소화설비 설치 공동주택은 인접대지경계선 후퇴 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m↑", strict: false }, note: "건축선: 특화경관지구 건축물 제외 / 인접경계: 상업지역 건축물 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 2m↑ / 준공업지역 외 3m↑", strict: true }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 2m↑", strict: false }, note: "전용공업지역·일반공업지역·산업단지 내 공장·창고는 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표에 '그 밖의 건축물'에 해당하는 항목 없음" },
    ] },
  { code: "47150", name: "김천시",
    refs: [A58, AD80, AD_BP, "김천시 건축 조례/제29조", "김천시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m 이상 / 연립주택 2m 이상 / 다세대주택 1m 이상", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 4m 이상 / 연립주택 2m 이상 / 다세대주택 1m 이상", strict: true }, note: "인접경계선 기준: 상업지역에서 자동식 소화설비 설치 공동주택은 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m 이상", strict: false }, note: "전용주거지역 건축물(공동주택 제외) 인접 대지경계선 후퇴" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m 이상", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "2m 이상", strict: false }, note: "건축선: 바닥면적 합계 1,000㎡ 이상 판매·숙박(일반숙박 제외)·문화집회·종교시설 / 인접경계: 상업지역 아닌 지역, 동일 용도 1,000㎡ 이상" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m 이상 / 준공업지역 외 3m 이상", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m 이상 / 준공업지역 외 1.5m 이상", strict: false }, note: "바닥면적 합계 500㎡ 이상 공장·창고 기준; 전용·일반공업지역 및 산업단지 내 건축물 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표에 '그 밖의 건축물'에 해당하는 항목 없음" },
    ] },
  { code: "47170", name: "안동시",
    refs: [A58, AD80, AD_BP, "안동시 건축 조례/제31조", "안동시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑ / 연립주택 3m↑ / 다세대주택 2m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "별표 건축선 후퇴만 규정(바. 공동주택); 인접 대지경계선 후퇴 별도 규정 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑ (한옥: 처마선 2m 이하, 외벽선 1m↑)", strict: false }, note: "인접 대지경계선 표 가. 전용주거지역 건축물(공동주택 제외); 건축선 후퇴 별도 규정 없음" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3,000㎡ 미만: 3m↑ / 3,000㎡ 이상: 5m↑", strict: true }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "해당 없음", strict: false }, note: "별표 건축선 후퇴 다.(1,000㎡↑ 판매·숙박·문화집회·종교시설); 면적 구간을 3,000㎡ 기준으로 세분화; 인접 대지경계선 후퇴 별도 규정 없음" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 2m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 2m↑", strict: false }, note: "건축선: 별표 가·나(공장·창고 500㎡↑); 인접경계: 별표 나(공장·창고 500㎡↑); 전용·일반공업지역 및 산업단지 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "준공업지역 2m↑ / 준공업지역 외 3m↑ (위험물저장처리시설 200㎡↑: 준공업 2m↑ / 외 4m↑)", strict: true }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "사. 그 밖의 건축물: 위험물저장처리시설(200㎡↑) 준공업 2m↑/외 4m↑, 자동차관련시설·관광휴게시설(500㎡↑) 준공업 2m↑/외 3m↑, 한옥 외벽선 1m↑; 인접 대지경계선 후퇴 별도 규정 없음" },
    ] },
  { code: "47210", name: "영주시",
    refs: [A58, AD80, AD_BP, "영주시 건축 조례/제34조", "영주시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m / 연립주택 2m / 다세대주택 1m", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "건축선 후퇴만 규정(별표 마목); 인접 대지경계선 후퇴 별표에 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m 이상", strict: false }, note: "인접경계 별표 가목: 전용주거지역 건축물(공동주택 제외) 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "바닥면적 합계 2,000㎡ 미만: 3m / 2,000㎡ 이상: 5m", strict: true }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "해당 없음", strict: false }, note: "건축선 후퇴 별표 다목(1,000㎡ 이상 판매·숙박·문화집회·종교시설); 인접경계 후퇴 별표에 없음" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역: 2m / 준공업지역 외: 3m", strict: true }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역: 1m 이상 / 준공업지역 외: 2m 이상", strict: true }, note: "건축선 별표 가·나목, 인접경계 별표 나목; 500㎡ 이상 공장·창고(전용·일반공업지역 및 산업단지 제외)" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "주거지역·상업지역 내 연면적 200㎡ 이상 건축물: 1m", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "건축선 별표 아목; 막다른 도로(길이 35m 미만) 및 시장이 곤란하다고 인정하는 건축물 제외" },
    ] },
  { code: "47250", name: "상주시",
    refs: [A58, AD80, AD_BP, "상주시 건축조례/제25조", "상주시 건축조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "해당 없음", strict: false }, note: "별표 건축선 후퇴 표에만 공동주택 규정 존재(마목); 인접 대지경계선 표에는 공동주택 항목 없음" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "인접 대지경계선 표 가목: 전용주거지역 건축물(공동주택 제외) 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "바닥면적 합계 2,000㎡ 미만: 3m↑ / 2,000㎡ 이상: 5m↑", strict: true }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "바닥면적 합계 2,000㎡ 미만: 3m↑ / 2,000㎡ 이상: 5m↑ (상업지역 제외)", strict: true }, note: "건축선·인접경계 모두 2,000㎡ 기준으로 3m↑/5m↑ 구분; 국가기준(1,000㎡↑ 3~6m)보다 세분화" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 2m↑ / 준공업지역 외 3m↑", strict: true }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 2m↑", strict: true }, note: "건축선 표 가·나목(공장·창고 500㎡↑); 인접경계 표 나목 기준 적용; 전용·일반공업지역 및 산업단지 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표 원문에 '그 밖의 건축물'에 해당하는 일반 항목 없음" },
    ] },
  { code: "47290", name: "경산시",
    refs: [A58, AD80, AD_BP, "경산시 건축 조례/제19조", "경산시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립주택 1.5m↑ / 다세대주택 1.5m↑ (상업지역 제외)", strict: true }, note: "인접 대지경계선 기준 상업지역에서 건축하는 공동주택은 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외), 인접 대지경계선 1m 이상" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑ (시장정비구역 내 도로 3면↑ 접하는 경우 1.5m↑, 2면↑ 접하는 경우 2m↑)", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m↑ (상업지역 제외)", strict: false }, note: "바닥면적 합계 1,000㎡ 이상 판매·숙박(여관·여인숙 제외)·문화집회(전시장·동식물원 제외)·종교시설" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 2m↑ / 준공업지역 외 3m↑", strict: true }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 2m↑", strict: true }, note: "바닥면적 합계 500㎡ 이상 공장·창고, 전용·일반공업지역 및 산업단지 제외; 공장은 배출시설 설치허가·신고 대상에 한함" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑ (상업지역 제외)", strict: false }, note: "그 밖의 건축물, 상업지역에서 건축하는 건축물은 인접 대지경계선 기준 제외" },
    ] },
  { code: "48220", name: "통영시",
    refs: [A58, AD80, AD_BP, "통영시 건축 조례/제15의2조", "통영시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑ / 연립주택 3m↑ / 다세대주택 2m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 5m↑ / 연립주택 3m↑ / 다세대주택 2m↑", strict: true }, note: "아파트·연립주택의 동당 100㎡ 이하 부대시설은 건축선 2m↑, 인접경계 아파트 2m↑·연립 1.5m↑ 적용; 상업지역 스프링클러 설치 공동주택은 인접경계 규정 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외)에 한함" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑(상업지역 아닌 곳): 3m↑", strict: true }, note: "판매시설·숙박시설(일반숙박 제외)·문화및집회시설(전시장·동식물원 제외)·종교시설 해당" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 2m↑ / 준공업지역 외 3m↑", strict: true }, note: "전용공업지역·일반공업지역·산업단지 내 공장·창고는 제외; 인접경계 준공업지역 2m↑는 국가 하한(1m↑) 대비 강화" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "2m↑", strict: true }, boundary: { nat: "0.5~6m", sel: "2m↑", strict: true }, note: "위험물저장·처리시설(영 별표1 제19호 가~라목), 자동차관련시설, 동물·식물관련시설(영 별표1 제21호 가~라목), 자원순환관련시설, 묘지관련시설 해당; 연면적 200㎡ 미만 축사 및 무허가 축사 적법화 대상은 제외" },
    ] },
  { code: "48240", name: "사천시",
    refs: [A58, AD80, AD_BP, "사천시 건축조례/제29조", "사천시 건축조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 5m↑ / 연립주택 2.5m↑ / 다세대주택 2m↑", strict: true }, note: "인접경계 기준: 상업지역 내 스프링클러 등 자동식 소화설비 설치 공동주택 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "2m↑", strict: false }, note: "전용주거지역 건축물(공동주택 제외), 인접경계 국가 하한(1m) 대비 2m로 상향" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "3m↑(상업지역 제외)", strict: true }, note: "바닥면적 합계 1,000㎡↑인 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접경계는 상업지역 건축물 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 그 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 2m↑ / 그 외 3m↑", strict: true }, note: "바닥면적 합계 500㎡↑인 공장·창고(전용·일반공업지역 및 산업단지 제외); 인접경계 준공업지역 국가 하한(1m) 대비 2m로 상향" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "해당 없음", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표에 '그 밖의 건축물'에 해당하는 일반 항목 없음; 마목(의료시설 등 특정 용도)만 별도 규정" },
    ] },
  { code: "48250", name: "김해시",
    refs: [A58, AD80, AD_BP, "김해시 건축 조례/제36조", "김해시 건축 조례/별표4"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트: 6m↑(30세대 미만 3m↑) / 연립주택: 2m↑ / 다세대주택: 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트: 6m↑(30세대 미만 3m↑) / 연립주택: 3m↑ / 다세대주택: 2m↑", strict: true }, note: "상업지역에 건축하는 공동주택으로서 스프링클러 등 자동식 소화설비를 설치한 공동주택은 인접 대지경계선 후퇴 적용 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "전용주거지역에 건축하는 건축물(공동주택 제외)" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "상업지역이 아닌 지역: 1.5m↑", strict: false }, note: "바닥면적 합계 1,000㎡↑인 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설 해당" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역: 1.5m↑ / 준공업지역 외: 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역: 1m↑ / 준공업지역 외: 1.5m↑", strict: false }, note: "전용공업지역·일반공업지역 및 산업단지 내 공장·창고는 적용 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "0.5m↑ (상업지역 주상복합 건축물 중 공동주택 외 용도: 1m↑)", strict: false }, note: "단독주택(단독주택에 한정) 및 연면적 150㎡ 미만 근린생활시설은 건축선 후퇴 적용 제외; 2면 이상 도로 접할 경우 넓은 도로 적용, 가로구역은 장변 접한 주도로 한정" },
    ] },
  { code: "48270", name: "밀양시",
    refs: [A58, AD80, AD_BP, "밀양시 건축 조례/제29조", "밀양시 건축 조례/별표2"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 3m↑ / 연립주택 2m↑ / 다세대주택 1m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 3m↑ / 연립주택 1.5m↑ / 다세대주택 1m↑", strict: true }, note: "상업지역에 건축하는 공동주택으로서 스프링클러 등 자동식 소화설비를 설치한 경우 인접대지경계선 후퇴 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑ (한옥의 경우 처마선 0.5m↑)", strict: false }, note: "전용주거지역 건축물(공동주택 제외) 기준" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1.5m↑", strict: false }, note: "건축선: 바닥면적 합계 1,000㎡↑인 판매·숙박(일반숙박 제외)·문화집회(전시장·동식물원 제외)·종교시설; 인접경계: 상업지역이 아닌 지역에 한함" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역 1.5m↑ / 준공업지역 외 3m↑", strict: false }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역 1m↑ / 준공업지역 외 1.5m↑", strict: false }, note: "바닥면적 합계 500㎡↑인 공장·창고 기준; 전용공업지역·일반공업지역·산업단지 내 건축 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "연면적 5,000㎡↑ 건축물: 1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표상 '그 밖의 건축물' 일반 규정은 없으며, 연면적 5,000㎡↑ 건축물에 대해 건축선 1m↑ 규정만 존재" },
    ] },
  { code: "48310", name: "거제시",
    refs: [A58, AD80, AD_BP, "거제시 건축 조례/제17의2조", "거제시 건축 조례/별표3"],
    uses: [
      { key: "gongdong", label: "공동주택", liner: { nat: "아파트 2~6m / 연립 2~5m / 다세대 1~4m", sel: "아파트 4m↑ / 연립주택 3m↑ / 다세대주택 2m↑", strict: true }, boundary: { nat: "아파트 2~6m / 연립 1.5~5m / 다세대 0.5~4m", sel: "아파트 4m↑ / 연립주택 2m↑ / 다세대주택 2m↑", strict: true }, note: "인접 대지경계선 기준: 상업지역 내 스프링클러 등 자동식 소화설비 설치 공동주택은 제외" },
      { key: "jeonju", label: "전용주거지역 건축물(공동주택 제외)", boundary: { nat: "1~6m", sel: "1m↑", strict: false }, note: "별표 인접 대지경계선 표 '가'항: 전용주거지역 건축물(공동주택 제외) — 수치 '미터 이상'으로만 기재되어 구체 수치 판독 불가(원문 '·미터 이상')" },
      { key: "panmae", label: "판매·숙박·문화집회·종교시설 등(대규모)", liner: { nat: "1,000㎡↑: 3~6m", sel: "1,000㎡↑: 3m↑", strict: false }, boundary: { nat: "1,000㎡↑(상업지역 아닌 곳): 1.5~6m", sel: "1,000㎡↑(상업지역 제외): 3m↑", strict: true }, note: "인접 대지경계선 기준: 상업지역에 건축하는 건축물은 제외" },
      { key: "gongjang", label: "공장·창고(바닥면적 500㎡↑)", liner: { nat: "준공업 1.5~6m / 그 외 3~6m", sel: "준공업지역: 2m↑(공장) / 1.5m↑(창고) / 준공업지역 외: 3m↑", strict: true }, boundary: { nat: "준공업 1~6m / 그 외 1.5~6m", sel: "준공업지역: 2m↑(공장) / 준공업지역 외: 3m↑", strict: true }, note: "건축선 기준 창고는 준공업지역 1.5m↑, 그 외 3m↑; 전용·일반공업지역 및 산업단지 내 공장·창고는 제외" },
      { key: "etc", label: "그 밖의 건축물", liner: { nat: "1~6m", sel: "다중이용건축물 2m↑ / 준다중이용건축물·5층 초과·연면적 1,000㎡↑ 건축물 1m↑", strict: false }, boundary: { nat: "0.5~6m", sel: "해당 없음", strict: false }, note: "별표에 '그 밖의 건축물' 일반 항목 없음; 마·바·사항(의료시설 등 2m↑, 다중이용 2m↑, 준다중이용·5층초과·1,000㎡↑ 1m↑)이 해당" },
    ] },
];
